server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes: []

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.oauth2.resource.reactive.ReactiveOAuth2ResourceServerAutoConfiguration

# --- Logging ---
logging:
  level:
    root: INFO
    com.pmfml.orderflow: DEBUG
