package com.pmfml.orderflow.inventoryservice.entities;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.UUID;

/**
 * Tracks the idempotency of consumed Kafka events.
 *
 * <p>To achieve exactly-once processing semantics over Kafka's at-least-once delivery,
 * every consumer must deduplicate incoming events based on their unique {@code eventId}.
 * This document stores the IDs of successfully processed events.
 */
@Document(collection = "processed_events")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ProcessedEvent {

    /**
     * The unique event ID generated by the producer. Maps to the {@code eventId}
     * in the canonical event envelope.
     */
    @Id
    private String id;

    private String eventType;

    /**
     * When this event was processed by this service.
     */
    private Instant processedAt;
    
    /**
     * Optional TTL index to automatically purge old processed events and prevent
     * the collection from growing indefinitely.
     */
    @Indexed(expireAfterSeconds = 7776000) // 90 days
    private Instant createdAt;
}
