#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE orders;
    CREATE DATABASE payments;
    GRANT ALL PRIVILEGES ON DATABASE orders TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE payments TO $POSTGRES_USER;
EOSQL
