spring:
  application:
    name: inventory-service

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27018/orderflow}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: inventory-group
      auto-offset-reset: earliest

server:
  port: 8092

logging:
  level:
    root: INFO
    com.pmfml.orderflow: DEBUG
