global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'order-flow-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8090' # API Gateway
          - 'host.docker.internal:8091' # Order Service
          - 'host.docker.internal:8092' # Inventory Service
          - 'host.docker.internal:8093' # Payment Service
